version: "3.8"
services:
  db:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: myapp_dev
    image: "postgres:11-alpine"
    restart: always
    volumes:
      - "pgdata:/var/lib/postgresql/data" # Persist data even if container is destroyed
    ports:
      - "5442:5432"

  web:
    build: .
    depends_on:
      - db
    environment:
            DATABASE_URL: postgres://postgres:postgres@db:5442/time_manager_dev

    ports:
      - "4000:4001"
    volumes:
      - .:/app

volumes:
  pgdata:
