version: "3.8"

services:
  db:
    image: "postgres:11-alpine"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: myapp_dev
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    ports:
      - "5442:5432"

  db_test:
    image: "postgres:11-alpine"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: myapp_test
    volumes:
      - "pgdata_test:/var/lib/postgresql/data"
    ports:
      - "5443:5432"

  web:
    build: .
    depends_on:
      - db_test
    environment:
      DATABASE_URL: postgres://postgres:postgres@db_test:5432/myapp_test
    ports:
      - "4000:4000"
    volumes:
      - .:/app

volumes:
  pgdata: {}
  pgdata_test: {}

networks:
  default:
    driver: bridge
