version: "3.8"
services:
  db:
    image: "postgres:11-alpine"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: myapp_dev
    ports:
      - "5442:5432"

  db_test:
    image: "postgres:11-alpine"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: myapp_test
    ports:
      - "5443:5432"

  web:
    build: .
    depends_on:
      - db
    environment:
            DATABASE_URL: postgres://postgres:postgres@db:5442/time_manager_dev

    ports:
      - "4000:4000"
    volumes:
      - .:/app

volumes:
  pgdata:
