version: "3.8"
services:
  db:
    image: "postgres:11-alpine"
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: myapp_dev
    volumes:
      - "pgdata:/var/lib/postgresql/data" # Persist data even if container is destroyed
    ports:
      - "5442:5432"

  db_test:
    image: "postgres:11-alpine"
    restart: always
    environment:
      POSTGRES_DB: myapp_test
    volumes:
      - "pgdata_test:/var/lib/postgresql/data"
    ports:
      - "5443:5432"

  web:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/myapp_dev
    ports:
      - "4000:4000" # Assuming your application listens on port 4001
    volumes:
      - .:/app

volumes:
  pgdata:
  pgdata_test: