name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:11-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: myapp_dev
        ports:
          - 5442:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.12'  # or the version you use
          otp-version: '24'  # or the version you use

    - name: Install dependencies
      run: mix deps.get
      working-directory: ./time_manager  # Change this to your project's folder

    - name: Run tests
      run: mix test
      working-directory: ./time_manager  # Change this to your project's folder
        
