name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:11-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: myapp_dev
        ports:
          - 5442:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.17.3'  # Update to 1.14 or higher
          otp-version: '27.0'       # Ensure this is compatible as well

      - name: Install dependencies
        run: mix deps.get
        working-directory: ./time_manager  # Adjust to your project's folder

      - name: Run tests
        run: mix test
        working-directory: ./time_manager  # Adjust to your project's folder
