name: CI  

on:
  push:
    branches:
      - dev  
  pull_request:
    branches:
      - dev  

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db_test:
        image: postgres:11-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: myapp_test
        ports:
          - 5443:5432  
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  

      - name: Set up Elixir
        uses: erlef/setup-beam@v1  
        with:
          elixir-version: '1.17.3' 
          otp-version: '27.0'  

    
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Install dependencies
        run: mix deps.get  
        working-directory: ./time_manager  

      - name: Set up database
        run: |
          mix ecto.create  # Create the database
          mix ecto.migrate  # Run migrations
        env:
          MIX_ENV: test  
        working-directory: ./time_manager  

      - name: Run tests
        run: mix test  
        env:
          MIX_ENV: test  
        working-directory: ./time_manager 
